const mutations = {
    SET_METAMASK_PROCESSING: 'SET_METAMASK_PROCESSING',
    SET_METAMASK_ACCOUNT: 'SET_METAMASK_ACCOUNT',
    SET_METAMASK_ACCOUNT_AUTHENTICATION: 'SET_METAMASK_ACCOUNT_AUTHENTICATION',
    SET_METAMASK_CHAIN: 'SET_METAMASK_CHAIN',
    SET_POOL: 'SET_POOL',
    SET_BOX_PRICE: 'SET_BOX_PRICE',
    SET_BOXES_AMOUNT: 'SET_BOXES_AMOUNT',
    SET_MY_NFT_LIST: 'SET_MY_NFT_LIST',
    SET_MY_WISHLIST: 'SET_MY_WISHLIST',
    SET_PRE_ORDER_LIST: 'SET_PRE_ORDER_LIST',
    SET_HISTORY_PHYSICAL_LIST: 'SET_HISTORY_PHYSICAL_LIST',
    SET_HISTORY_DIGITAL_LIST: 'SET_HISTORY_DIGITAL_LIST',
    SET_ACTIVITY_LIST: 'SET_ACTIVITY_LIST',
    SET_PRE_ORDER_QUANTITY: 'SET_PRE_ORDER_QUANTITY',
    SET_DATA_PRE_ORDER: 'SET_DATA_PRE_ORDER',
    SET_DATA_BUY_ORDER: 'SET_DATA_BUY_ORDER',
    SET_DATA_REDEEM_ORDER: 'SET_DATA_REDEEM_ORDER',
    SET_DATA_MINT_ORDER: 'SET_DATA_MINT_ORDER',
    SET_DATA_MY_PROFILE: 'SET_DATA_MY_PROFILE',
    SET_DATA_MY_ADDRESS: 'SET_DATA_MY_ADDRESS',
    SET_DATA_AUTHENTICATOR_NFT: 'SET_DATA_AUTHENTICATOR_NFT',
    SET_DATA_SUBSCRIBE_PRODUCT: 'SET_DATA_SUBSCRIBE_PRODUCT',
    SET_APPROVE_STATUS: 'SET_APPROVE_STATUS',
    SET_MINT_STATUS: 'SET_MINT_STATUS',
    SET_BURN_STATUS: 'SET_BURN_STATUS',
    SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
    SET_POPULAR_CATEGORIES: 'SET_POPULAR_CATEGORIES',
    SET_LIMITED_EDITION: 'SET_LIMITED_EDITION',
    SET_NFT_MARKETPLACE: 'SET_NFT_MARKETPLACE'
}

const actions = {
    CONNECT_METAMASK: 'CONNECT_METAMASK',
    DISCONNECT_METAMASK: 'DISCONNECT_METAMASK',
    REQUEST_METAMASK_CHAIN_CHANGE: 'REQUEST_METAMASK_CHAIN_CHANGE',
    ONCE_METAMASK_CHAIN_CHANGE: 'ONCE_METAMASK_CHAIN_CHANGE',
    NCM_API_PRE_ORDER: 'NCM_API_PRE_ORDER',
    NCM_API_BUY_ORDER: 'NCM_API_BUY_ORDER',
    DETECT_MY_NFT_LIST: 'DETECT_MY_NFT_LIST',
    DETECT_HISTORY_LIST: 'DETECT_HISTORY_LIST',
    DETECT_ACTIVITY_LIST: 'DETECT_ACTIVITY_LIST',
    NCM_API_MINT_MY_PRE_ORDER: 'NCM_API_MINT_MY_PRE_ORDER',
    NCM_API_REDEEM_MY_NFT: 'NCM_API_REDEEM_MY_NFT',
    NCM_API_PRODUCT_WISHLIST: 'NCM_API_PRODUCT_WISHLIST',
    MY_PROFILE: 'MY_PROFILE',
    EDIT_MY_PROFILE: 'EDIT_MY_PROFILE',
    EDIT_MY_ADDRESS: 'EDIT_MY_ADDRESS',
    AUTHENTICATOR_NFT: 'AUTHENTICATOR_NFT',
    SUBSCRIBE_PRODUCT: 'SUBSCRIBE_PRODUCT',
    SEND_EMAIL_CONTACT_US: 'SEND_EMAIL_CONTACT_US',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_POPULAR_CATEGORIES: 'GET_POPULAR_CATEGORIES',
    GET_LIMITED_EDITION: 'GET_LIMITED_EDITION',
    GET_NFT_MARKETPLACE: 'GET_NFT_MARKETPLACE'
}

const getters = {
    isMetamaskConnected: 'isMetamaskConnected',
    isMetamaskProcessing: 'isMetamaskProcessing',
    metamaskAccount: 'metamaskAccount',
    metamaskChain: 'metamaskChain',
    accountAuthentication: 'accountAuthentication',
    myNftList: 'myNftList',
    myWishList: 'myWishList',
    userModel: 'userModel',
    userAddress: 'userAddress',
    responseBuyOrder: 'responseBuyOrder',
    responseRedeemOrder: 'responseRedeemOrder',
    responseMintOrder: 'responseMintOrder',
    responseAuthenticatorNft: 'responseAuthenticatorNft',
    responseSubscribeProduct: 'responseSubscribeProduct',
    preorderList: 'preorderList',
    physicalList: 'physicalList',
    digitalList: 'digitalList',
    activityList: 'activityList',
    approveStatus: 'approveStatus',
    mintStatus: 'mintStatus',
    burnStatus: 'burnStatus',
    responseProductDetail: 'productDetail',
    responsePopularCategories: 'responsePopularCategories',
    responseLimitedEdition: 'responseLimitedEdition',
    responseNftMarketplace: 'responseNftMarketplace'
}

export const vuexTypes = {
    ...mutations,
    ...actions,
    ...getters,
}
